import type { Ukm } from "@shared/schema";

export const ukmList: Ukm[] = [
  // Bela Diri (8 UKMs)
  {
    id: "karate-do",
    nama: "Karate-Do",
    bidang: "Bela Diri",
    deskripsi: "UKM Karate-Do ITS merupakan unit kegiatan mahasiswa yang bergerak di bidang bela diri dan telah berdiri sejak tahun 1973. Karate sendiri merupakan sebuah beladiri dengan tangan kosong yang berasal dari Jepang.",
    logo: "https://lh3.googleusercontent.com/d/14vf3xOSesZ40RnKYOOeuVa_93WYF0QVD",
    instagram: "https://instagram.com/ukmkaratedoits",
    memberCount: null,
    established: null,
    achievements: "25+",
    rating: "4.8",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "shorinji-kempo",
    nama: "Shorinji Kempo",
    bidang: "Bela Diri",
    deskripsi: "UKM Shorinji Kempo ITS merupakan UKM yang menggeluti Kempo. Beladiri ini berasal dari Jepang yang metode latihan sesuai filosofi 'jiwa dan tubuh adalah sebuah kesatuan yang tak terpisahkan' (shinshin ichinyo) dan 'melatih tubuh dan jiwa' (kenzen ichinyo). Dengan demikian Kempo mempunyai tiga manfaat: 'pelatihan dan pertahanan diri' (goshin rentan), 'pelatihan mental' (seishin shuyo) dan 'meningkatkan kesehatan' (kenko zoshin).",
    logo: "https://lh3.googleusercontent.com/d/1FZ2HwKJYyFKILAnto3Z8vfJR_hmsgwWO",
    instagram: "https://instagram.com/shorinjikempoits",
    memberCount: null,
    established: null,
    achievements: "20+",
    rating: "4.7",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "kendo",
    nama: "Kendo",
    bidang: "Bela Diri",
    deskripsi: "Kendo merupakan seni beladiri Jepang yang menggunakan pedang bambu dan pelindung tubuh. Di negara asalnya, Jepang, Kendo menjadi pilihan pelajaran wajib di tingkat SMP.",
    logo: "https://lh3.googleusercontent.com/d/1tnLQ6VWmNq7EgPihG2QLCcCvOk_haHO9",
    instagram: "https://instagram.com/kendoits",
    memberCount: null,
    established: null,
    achievements: "15+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "merpati-putih",
    nama: "Merpati Putih (MP)",
    bidang: "Bela Diri",
    deskripsi: "UKM Merpati Putih ITS merupakan suatu wadah penyaluran minat bakat Mahasiswa dalam bidang bela diri. UKM Merpati Putih sendiri singkatan dalam bahasa jawa, yaitu 'Mersudi Patitising Tindak Pusakane Hening' atau yang dalam bahasa indonesia berarti 'Mencari sampai mendapat Kebenaran dengan Ketenangan'. Sehingga diharapkan, anggota Merpati Putih akan menyelaraskan hati dan pikiran dalam setiap tindakannya. Hal yang membedakan Merpati Putih dengan Beladiri yang lainnya adalah Teknik Olah Nafas dan Tenaga Dalam.",
    logo: "https://lh3.googleusercontent.com/d/1Bi-4UeHuHNhHp1eHqAtuW0e3gIKI1lVm",
    instagram: "https://instagram.com/merpati_putih_its",
    memberCount: null,
    established: null,
    achievements: "18+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "muay-thai",
    nama: "Muay Thai",
    bidang: "Bela Diri",
    deskripsi: "IMA memiliki fokus untuk melatih dan mengajarkan seni beladiri Muay Thai yang berasal dari Thailand. IMA juga merupakan fasilitator bagi anggotanya yang ingin mendalami kegiatannya sekaligus mengikuti kompetisi kejuaraan.",
    logo: "https://lh3.googleusercontent.com/d/1tPW6BFWiCzTcpVh5OHYBoRiVM_AnAmOf",
    instagram: "https://instagram.com/itsmuaythai",
    memberCount: null,
    established: null,
    achievements: "12+",
    rating: "4.4",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "taekwondo",
    nama: "Taekwondo",
    bidang: "Bela Diri",
    deskripsi: "UKM Taekwondo ITS merupakan organisasi yang menaungi mahasiswa ITS dalam bidang beladiri taekwondo. UKM Taekwondo ITS telah berdiri sejak tahun 1999. Melalui UKM Taekwondo ITS, kalian akan mendapatkan pengembangan skills tidak hanya dalam ranah keatletan, tetapi juga dalam hal manajerial organisasi.",
    logo: "https://lh3.googleusercontent.com/d/1uYBGjEoZfjQg__bRD6MZFUxZmLDnFqeN",
    instagram: "https://instagram.com/taekwondo_its",
    memberCount: null,
    established: null,
    achievements: "22+",
    rating: "4.7",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "perisai-diri",
    nama: "Perisai Diri",
    bidang: "Bela Diri",
    deskripsi: "Perisai Diri Unit ITS mengajarkan pesilat mengenai teknik bela diri yang efektif dan efisien, baik tangan kosong maupun dengan senjata. Metode praktis dalam Perisai Diri adalah latihan serang hindar yang menghasilkan motto 'Pandai Silat Tanpa Cidera'.",
    logo: "https://lh3.googleusercontent.com/d/1Bh_ODsS3uu7Kyw_U0fORl6lrEUVnKMAx",
    instagram: "https://instagram.com/perisaidiri_its",
    memberCount: null,
    established: null,
    achievements: "16+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "psht",
    nama: "PSHT",
    bidang: "Bela Diri",
    deskripsi: "PSHT merupakan suatu persaudaraan 'perguruan' silat yang bertujukan membentuk manusia berbudi luhur, mengetahui benar dan salah bertakwa pada Tuhan Yang Maha Esa dan mengajarkan kesetiaan pada hati sanubari serta mengutamakan persaudaraan antar anggota. UKM satu ini juga tidak kalah dalam mencetak prestasi.",
    logo: "https://lh3.googleusercontent.com/d/1ekmHDpOgCwhnf2zJpfVK4NSYleP-rSmm",
    instagram: "https://instagram.com/psht_its",
    memberCount: null,
    established: null,
    achievements: "14+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },

  // Olahraga (15 UKMs)
  {
    id: "ibc",
    nama: "IBC (Badminton)",
    bidang: "Olahraga",
    deskripsi: "Badminton merupakan salah satu olahraga kejayaan Indonesia. Jika kamu suka berlarian mengejar bulu tangkis dan bergerak aktif, UKM ini adalah tempat yang sesuai untuk kamu. Latih badanmu dan temukan orang dengan hobi sama disini, dan temukan rumah keduamu di ITS.",
    logo: "https://lh3.googleusercontent.com/d/1XeOlD3WX-D0UHH8XZYJ-o0xQRrG07IGE",
    instagram: "https://instagram.com/ukm_badminton_its",
    memberCount: null,
    established: null,
    achievements: "40+",
    rating: "4.9",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "basketball",
    nama: "ITS Basketball",
    bidang: "Olahraga",
    deskripsi: "Jika kamu menyukai olahraga bola basket, UKM basket ITS bisa menjadi pilihan kamu untuk mengembangkan skill. Tak hanya untuk kompetisi bola basket, namun juga untuk bermain dan berkomunitas dengan orang ber-passion sama dengan kamu. Lihat keseruan UKM bola basket disini.",
    logo: "https://lh3.googleusercontent.com/d/1R9sokza6iRuD0pAeHgsX0yyb4_i9czH4",
    instagram: "https://instagram.com/ukmbasketits",
    memberCount: null,
    established: null,
    achievements: "35+",
    rating: "4.8",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "billiard",
    nama: "ITS Billiard",
    bidang: "Olahraga",
    deskripsi: "Kamu suka bermain biliard? di ITS terdapat UKM biliard yang menjadi rumah bagi kalian yang hobi dan passion sama.",
    logo: "https://lh3.googleusercontent.com/d/1uPYtln2VN7iR4FX7hystAocbTVC6bAgx",
    instagram: "https://instagram.com/itsbilliard",
    memberCount: null,
    established: null,
    achievements: "10+",
    rating: "4.3",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "bridge",
    nama: "Bridge",
    bidang: "Olahraga",
    deskripsi: "Tak sekedar bermain, UKM ini juga mengajari kamu strategi, sportifitas dan juga memacu kamu untuk berkompetisi hingga tingkat internasional. Lihat selengkapnya disini.",
    logo: "https://lh3.googleusercontent.com/d/1qaIutfNrVDbTfFHpwK_5QwXI10c2oeeo",
    instagram: "https://instagram.com/bridge.its",
    memberCount: null,
    established: null,
    achievements: "8+",
    rating: "4.2",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "catur",
    nama: "Catur",
    bidang: "Olahraga",
    deskripsi: "Bagi kalian yang menyukai catur, ITS memiliki UKM catur yang menampung hobi kamu dalam bermain permainan papan ini. Ikuti serunya kegiatan UKM catur di ITS disini.",
    logo: "https://lh3.googleusercontent.com/d/1FEL4W3Y-kB-cl0govxPtBBZpL2yW8hZe",
    instagram: "https://instagram.com/ucitssepuluhnopember",
    memberCount: null,
    established: null,
    achievements: "12+",
    rating: "4.1",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "flag-football",
    nama: "Flag Football",
    bidang: "Olahraga",
    deskripsi: "UKM yang berdiri pada tahun 2013 ini, merupakan wadah bagi mahasiswa ITS yang minat dan bakatnya di olahraga flag football. UKM Flag Football ini memiliki nama lain yaitu Seaborg, atau nama tim dari UKM Flag Football ini sendiri. UKM ini telah mengikuti banyak perlombaan dan diantaranya menjadi juara, diantaranya perlombaan nasional College Bowl dan Surabaya Flag Football League. Kegiatan UKM Flag Football sendiri ada latihan rutin, welcoming party, internalisasi.",
    logo: "https://lh3.googleusercontent.com/d/1I6rDl1CSOqDTCFxeouJ0wFkQBrmmu6ab",
    instagram: "https://instagram.com/its.flagfootball",
    memberCount: null,
    established: null,
    achievements: "8+",
    rating: "4.4",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "voli",
    nama: "ITS Voli",
    bidang: "Olahraga",
    deskripsi: "UKM Volleyball ITS didirikan pada tahun 2016 atas rekomendasi Lembaga Minat Bakat (LMB) dari komunitas penggemar volleyball ITS. Walau baru 4 tahun, UKM Volleyball ITS sudah mampu menembus 8 besar nasional dalam kejuaraan voli antar perguruan tinggi. Kegiatan-kegiatan yang ada di UKM Volleyball ITS ini antara lain latihan rutin, sparing, POMITS, dan Pires. UKM Volleyball melakukan latihan rutinnya di Kampus Manyar.",
    logo: "https://lh3.googleusercontent.com/d/1_9AlfpPGQGeO3ALI8P9N3TLZb0L3JnnH",
    instagram: "https://instagram.com/ukmvoli.its",
    memberCount: null,
    established: null,
    achievements: "15+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "sepakbola",
    nama: "Sepakbola",
    bidang: "Olahraga",
    deskripsi: "Sepakbola merupakan salah satu olahraga paling populer di dunia. Jika kamu menyukai sepak bola, UKM Sepak Bola ITS bisa menjadi pilihan kamu untuk mengembangkan skill. Tak peduli kamu ingin jadi juara lapangan hijau atau sekedar bermain, kamu akan menemukan rumah disini. Lihat keseruan UKM bola basket disini.",
    logo: "https://lh3.googleusercontent.com/d/1QW1nnokzoJ2h9gIamW8dAE2aBUxNlAt2",
    instagram: "https://instagram.com/ukmsepakbolaits",
    memberCount: null,
    established: null,
    achievements: "50+",
    rating: "4.8",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "tenis-lapangan",
    nama: "Tenis Lapangan",
    bidang: "Olahraga",
    deskripsi: "Kamu suka olahraga yang menguatkan badan dan lengan? tenis bisa menjadi olahraga untuk mengembangkan hobi kamu. Disini kamu akan bertemu dengan orang dengan hobi sama hingga keluarga baru dengan ketertarikan sama. Llihat keseruan UKM ini disini.",
    logo: "https://lh3.googleusercontent.com/d/1Nw8BxyKoiJPupK0TLFXTdj9RTuEOd0QN",
    instagram: "https://instagram.com/tennis_its",
    memberCount: null,
    established: null,
    achievements: "20+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "softball",
    nama: "Softball",
    bidang: "Olahraga",
    deskripsi: "Softball merupakan olahraga beregu yang terdiri dari 2 tim dimana setiap tim akan bergantian menjadi pemukul dan penjaga. UKM Softball ITS berdiri pada tahun 2015. UKM ini memiliki nama lain yaitu Stingray, yang dimana Stringray sendiri merupakan nama tim dari softball ITS. Kegiatan UKM Softball dilakukan di Taman Alumni. Perlombaan yang pernah diikuti oleh UKM Softball adalah Liga Mahasiswa, UGM CUP, REDFOX, dan Unair Cup.",
    logo: "https://lh3.googleusercontent.com/d/1qpTy0C0YhH6BUafSBYVAY55Wlei7QYI9",
    instagram: "https://instagram.com/ukmsoftballits",
    memberCount: null,
    established: null,
    achievements: "6+",
    rating: "4.3",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "its-archery",
    nama: "ITS Archery (ITSA)",
    bidang: "Olahraga",
    deskripsi: "ITS Archery merupakan UKM yang baru berdiri pada tahun 2019. UKM yang berslogan 'membidik dengan hati ini' sebelumnya berawal dari komunitas ITS Archery. UKM ITS Archery memiliki beberapa kegiatan diantaranya latihan rutin, fun games, dan internal archery competition (INARCO). Prestasi yang pernah diraih oleh UKM ini antara lain Juara 1 Horsebow Ground Archery RH2C Competition 2020 dan Juara 3 Lomba Field Archery 2019.",
    logo: "https://lh3.googleusercontent.com/d/1enxlQLkA4eUEBKywmxKp8bu7PcGyVAb-",
    instagram: "https://instagram.com/archeryits",
    memberCount: null,
    established: null,
    achievements: "5+",
    rating: "4.4",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "hde",
    nama: "HDE",
    bidang: "Olahraga",
    deskripsi: "Heroes Day E-Sports (HDE) adalah wadah pengembangan yang cocok untuk kalian yang tertarik di bidang E-Sport. Bagi kalian yang ingin bermain games sekaligus dapat banyak benefit UKM ini sangat cocok di ikuti.",
    logo: "https://lh3.googleusercontent.com/d/1ddBn0U6bPbDfNsAFOTPWvbLPmpTOj7rM",
    instagram: "https://instagram.com/its.heroesdayesports",
    memberCount: null,
    established: null,
    achievements: "10+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "golf",
    nama: "GOLF",
    bidang: "Olahraga",
    deskripsi: "Golf ITS adalah salah satu UKM Bidang Olahraga yang berfokus pada permainan golf. Di UKM ini kalian akan diajari gimana cara bermain yang benar.",
    logo: "https://lh3.googleusercontent.com/d/1ROOuFk05VAlOjgFo15AnWSkMChc5v3eR",
    instagram: "https://instagram.com/ukm_golfits",
    memberCount: null,
    established: null,
    achievements: "4+",
    rating: "4.2",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "tenis-meja",
    nama: "Tenis Meja",
    bidang: "Olahraga",
    deskripsi: "Tenis Meja ITS adalah salah satu calon UKM yang mewadahi pengembangan mahasiswa yang berfokus pada tenis meja. Buat kalian yang suka permainan ini boleh banget join karena dijamin asik.",
    logo: "https://lh3.googleusercontent.com/d/1lp4J-qzPwmond2_YYYpvOqNOz1O0B0Ld",
    instagram: "https://instagram.com/tenismeja.its",
    memberCount: null,
    established: null,
    achievements: "3+",
    rating: "4.0",
    email: null,
    location: null,
    isActive: 1
  },

  // Seni (7 UKMs)
  {
    id: "rebana-uri",
    nama: "Rebana (URI)",
    bidang: "Seni",
    deskripsi: "UKM Rebana merupakan UKM yang melestarikan seni tradisional Hazarah Banjari . Temukan ekspresimu lewat seni musik ini dan temukan keluarga yang berbagi passion dan kecintaan denganmu.",
    logo: "https://lh3.googleusercontent.com/d/16K1rvpPLxs5VSGEevc9_SsmRpj__32lo",
    instagram: "https://instagram.com/ukmrebanaits",
    memberCount: null,
    established: null,
    achievements: "15+",
    rating: "4.4",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "musik",
    nama: "Musik",
    bidang: "Seni",
    deskripsi: "UKM Musik bisa jadi pilihan kamu. Tak peduli kamu suka menyanyi, atau bermain musik, kamu akan diterima disini. Tak sedikit anggota UKM Musik yang melalangbuana dalam pentas dan kompetisi.",
    logo: "https://lh3.googleusercontent.com/d/1LmiCb31JRHg_1UG0iFhoe3_gS08TuT28",
    instagram: "https://instagram.com/musikits",
    memberCount: null,
    established: null,
    achievements: "30+",
    rating: "4.7",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "psm",
    nama: "PSM ITS",
    bidang: "Seni",
    deskripsi: "Paduan Suara Mahasiswa (PSM) ITS adalah tempat terbaik bagi kamu untuk belajar. Tak hanya soal paduan suara, kamu juga akan ditempa menjadi tim yang handal hingga ke kompetisi internasional.",
    logo: "https://lh3.googleusercontent.com/d/18pnUxdIhV0GUClk5-pmc8p8AxVzaOqbe",
    instagram: "https://instagram.com/itschoir",
    memberCount: null,
    established: null,
    achievements: "50+",
    rating: "4.9",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "teater",
    nama: "Teater Tiyang Alit",
    bidang: "Seni",
    deskripsi: "Bergabunglah bersama Teater Tiyang Alit dan tenggelamkan dirimu dalam lakon dan cerita bersama orang dengan passion sama.",
    logo: "https://lh3.googleusercontent.com/d/19P_LxhoE57riQW71kAFGVW3tHKz55irM",
    instagram: "https://instagram.com/teatertiyangalit",
    memberCount: null,
    established: null,
    achievements: "20+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "ukafo",
    nama: "UKAFO",
    bidang: "Seni",
    deskripsi: "UKAFO menyatukan orang dengan hobi fotografi dan menjadi wadah yang tepat untuk belajar fotografi. Kembangkan passionmu dan temukan keluarga baru disini! Pelajari lebih lanjut tentang UKAFO disini.",
    logo: "https://lh3.googleusercontent.com/d/1QAzwf5Iv_lmg_BW37KMpkcuxi2xxkHGY",
    instagram: "https://instagram.com/ukafo_its",
    memberCount: null,
    established: null,
    achievements: "25+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "uktk",
    nama: "UKTK",
    bidang: "Seni",
    deskripsi: "Di sini kamu bisa mengembangkan minatmu dibidang tari tradisional, modern dan juga seni karawitan.",
    logo: "https://lh3.googleusercontent.com/d/123_Yd0vYgJz-xUQ24PYj2Ih0YGrUteUD",
    instagram: "https://instagram.com/uktkits",
    memberCount: null,
    established: null,
    achievements: "18+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "vsnmc",
    nama: "VSNMC",
    bidang: "Seni",
    deskripsi: "VSNMC atau Victory Sepuluh Nopember Marching Corps yang merupakan wadah minat bakat mahasiswa ITS dalam bidang Marching Band. Jika kamu suka bermain musik dalam grup besar, maka VSNMC adalah tempat yang tepat bagi kamu untuk berekspresi.",
    logo: "https://lh3.googleusercontent.com/d/1yU2-6H6dlqrWisKNSwkTRIsFcBkjsVqE",
    instagram: "https://instagram.com/vsnmc_its",
    memberCount: null,
    established: null,
    achievements: "35+",
    rating: "4.8",
    email: null,
    location: null,
    isActive: 1
  },

  // Khusus (14 UKMs)
  {
    id: "astronomy",
    nama: "ITS Astronomy Club",
    bidang: "Khusus",
    deskripsi: "Jika kamu juga takjub dengan fenomena yang menciptakan alam semesta, perilaku benda langit dan dunia tempat kita hidup, maka UKM ini adalah tempat yang cocok untuk kamu.",
    logo: "https://lh3.googleusercontent.com/d/1PqR76fU3kVOwOBjBMaVcSxQQ3-Mt-259",
    instagram: "https://instagram.com/its_astronomyclub",
    memberCount: null,
    established: null,
    achievements: "15+",
    rating: "4.7",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "ifls",
    nama: "IFLS",
    bidang: "Khusus",
    deskripsi: "IFLS adalah UKM yang bergerak dalam bidang Bahasa dan Budaya Asing. Terdiri dari divisi ITS Debating Society, Jepang, Korea, Dueling Cards, dan IFLS Culture.",
    logo: "https://lh3.googleusercontent.com/d/1Wl1WuUJBsfXvb-sE1zzcGA0IOekHdcB-",
    instagram: "https://instagram.com/ifls_its",
    memberCount: null,
    established: null,
    achievements: "40+",
    rating: "4.8",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "kopma",
    nama: "KOPMA",
    bidang: "Khusus",
    deskripsi: "UKM Kopma Dr Angka bisa menjadi tempat yang tepat bagi kamu untuk berkembang. Tak sekedar UKM, Kopma Dr Angka juga telah dipercaya dalam produksi berbagai produk ITS serta pemasarannya.",
    logo: "https://lh3.googleusercontent.com/d/1kAL-u9quZ04cvasMu7UpS5fgREg6rAyQ",
    instagram: "https://instagram.com/kopma_its",
    memberCount: null,
    established: null,
    achievements: "25+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "ksr-pmi",
    nama: "KSR-PMI",
    bidang: "Khusus",
    deskripsi: "KSR PMI ITS merupakan Unit kegiatan yang menggembangkan kemampuan di bidang kepalangmerahan dan kesehatan. Unit ini mengembangkan kemampuan anggota melalui kegiatan-kegiatan pengabdian masyarakat seperti pekan kesehatan.",
    logo: "https://lh3.googleusercontent.com/d/18G9lvpOFrPB0azT6lN0SN_nhp3sc660V",
    instagram: "https://instagram.com/ksrpmiits",
    memberCount: null,
    established: null,
    achievements: "30+",
    rating: "4.7",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "lpm-1-0",
    nama: "LPM 1.0",
    bidang: "Khusus",
    deskripsi: "Disini kalian akan bertemu dan berinteraksi dengan sesama mahasiswa yang hobi menuangkan pemikiran dan peristiwa di sekitarnya lewat berbagai tulisan jurnalistik.",
    logo: "https://lh3.googleusercontent.com/d/1ZQ9QL5-Kb982RHBODA1Psa3xkH9y1N00",
    instagram: "https://instagram.com/satukosong_its",
    memberCount: null,
    established: null,
    achievements: "22+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "maritime-challenge",
    nama: "Maritime Challenge",
    bidang: "Khusus",
    deskripsi: "ITS memiliki UKM bagi kalian yang mencintai dan ingin mempelajari budaya maritim Indonesia. Tidak hanya belajar mengenai transportasi maritim, kalian juga bisa mengolah fisik dengan menjadi tim dayung MC yang sudah menyebrang laut hingga ke Eropa.",
    logo: "https://lh3.googleusercontent.com/d/1IzJp_ZGEOO__Gx-z6JTS-7t2xwRmm-ao",
    instagram: "https://instagram.com/maritime.challenge",
    memberCount: null,
    established: null,
    achievements: "12+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "penalaran",
    nama: "Penalaran",
    bidang: "Khusus",
    deskripsi: "UKM penalaran adalah tempat bagi kalian yang suka berpikir dan berjiwa kritis. Ini juga rumah bagi kalian yang selalu haus pada ilmu pengetahuan.",
    logo: "https://lh3.googleusercontent.com/d/1diC5bvOKhHTgpYRzxLEaHfM_e0TBs3Kx",
    instagram: "https://instagram.com/penalaranits",
    memberCount: null,
    established: null,
    achievements: "20+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "menwa",
    nama: "UKM Menwa",
    bidang: "Khusus",
    deskripsi: "Resimen Mahasiswa (MENWA) 802-ITS merupakan wadah penyaluran potensi mahasiswa dalam rangka mewujudkan hak dan kewajiban warga negara dalam bela negara. Melalui Menwa, mahasiswa dilatih untuk lebih disiplin, berpengetahuan luas, berfisik kuat, dan bermental baja.",
    logo: "https://lh3.googleusercontent.com/d/1ca0RbwVmKKwSc-XCInNpLd47C680qWHr",
    instagram: "https://instagram.com/menwaits",
    memberCount: null,
    established: null,
    achievements: "28+",
    rating: "4.7",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "pramuka",
    nama: "Pramuka",
    bidang: "Khusus",
    deskripsi: "UKM Pramuka ITS merupakan pangkalan dari gugus depan Surabaya 610 dan Surabaya 611. Pramuka ITS terus berusaha mengubah mindset masyarakat tentang pramuka pada umumnya menjadi pramuka dengan wawasan teknologi.",
    logo: "https://lh3.googleusercontent.com/d/1o4Qs9s3LCWZPv2hgLoYQ5Ub5wiVKKOuN",
    instagram: "https://instagram.com/pramuka.its",
    memberCount: null,
    established: null,
    achievements: "30+",
    rating: "4.7",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "robotik",
    nama: "Robotik",
    bidang: "Khusus",
    deskripsi: "Robotika merupakan salah satu gengsi perguruan tinggi teknik. Dan Robotika ITS sudah punya reputasi mentereng di tingkat nasional sampai internasional. Disini kalian akan belajar mengenai seluk beluk robot mulai dari robot humanoid, pemadam api hingga penari.",
    logo: "https://lh3.googleusercontent.com/d/1JHjYHhhY8ikqXSdel0CbmCCK9Fho9qEZ",
    instagram: "https://instagram.com/its.robotics",
    memberCount: null,
    established: null,
    achievements: "60+",
    rating: "4.9",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "plh-siklus",
    nama: "PLH Siklus",
    bidang: "Khusus",
    deskripsi: "UKM yang memiliki ranah sosial dan lingkungan serta berfokus pada konservasi Lingkungan. Selain itu terdapat 4 (empat) olahraga pengiring kegiatan PLH SIKLUS ITS yaitu Rock Climbing, Rafting, Caving, dan Mountaineering.",
    logo: "https://lh3.googleusercontent.com/d/19HfJHqd5gLoX-zJD05d8Ez0DWXOm4CwI",
    instagram: "https://instagram.com/plhsiklusits",
    memberCount: null,
    established: null,
    achievements: "18+",
    rating: "4.6",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "tdc",
    nama: "TDC ITS",
    bidang: "Khusus",
    deskripsi: "Technopreneurship Development Center merupakan UKM yang tepat bagi kalian yang passionate dalam bidang wirausaha dan ingin membuat usaha secara mandiri. Di bawah bimbingan pengajar di ITS, anggota UKM TDC akan berkumpul bersama sesama pengusaha untuk menggodok dan mengembangkan usahanya.",
    logo: "https://lh3.googleusercontent.com/d/17aA24klanj5Q8wVjHpJoPB5wG9u3FTjK",
    instagram: "https://instagram.com/tdcits",
    memberCount: null,
    established: null,
    achievements: "15+",
    rating: "4.5",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "mun",
    nama: "MUN",
    bidang: "Khusus",
    deskripsi: "ITS MUN Club merupakan tempat paling tepat bagi kamu untuk berkembang. Di bawah IFLS, ITS MUN Club mewadahi skill kamu dalam simulasi sidang Persatuan Bangsa-Bangsa (PBB).",
    logo: "https://lh3.googleusercontent.com/d/1lskb0vgi7rzXE6ogmhac76LqH5Lyzdrq",
    instagram: "https://instagram.com/itsmunclub",
    memberCount: null,
    established: null,
    achievements: "12+",
    rating: "4.4",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "ukm-automotive",
    nama: "UKM Automotive",
    bidang: "Khusus",
    deskripsi: "UKM Otomotif ITS merupakan salah satu calon UKM yang menaungi 5 tim riset mobil, yaitu Anargya ITS EV Team, Antasena ITS Team, Nogogeni ITS Team, ITS Team Sapuangin, dan Spektronics ITS Chem-E Car Team. UKM Otomotif ITS dibentuk atas dasar penanaman kepedulian dan kesadaran terhadap isu perubahan iklim dan penghematan energi.",
    logo: "https://lh3.googleusercontent.com/d/1OQ5SjDQ_rL5yUPkRqLai29t57FpM6_Q0",
    instagram: "https://instagram.com/automotiveteam.its",
    memberCount: null,
    established: null,
    achievements: "10+",
    rating: "4.3",
    email: null,
    location: null,
    isActive: 1
  },
  {
    id: "its-quran-society",
    nama: "ITS Quran Society",
    bidang: "Khusus",
    deskripsi: "ITS Society For Quranic Studies adalah salah satu calon UKM yang berfokus pada pengembangan seni qur'ani yang diperlombakan di Musabaqoh Tilawatil Qur'an Mahasiswa Nasional (MTQMN).",
    logo: "https://lh3.googleusercontent.com/d/1Kmp5Jyb1tlDlocnMGSY8ciVBiicnwg7k",
    instagram: "https://instagram.com/iqs.its",
    memberCount: null,
    established: null,
    achievements: "8+",
    rating: "4.2",
    email: null,
    location: null,
    isActive: 1
  }
];